version: '3.8'
services:
  HSC:
    container_name: HSC
    image: solr:8.10.1
    ports:
     - "8983:8983"
    environment:
     - ZK_HOST=zoo1:2181
    networks:
     - solr
    depends_on:
     - zoo1

  zoo1:
    image: zookeeper:latest
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
    - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    networks:
     - solr

  create-collection:
    image: solr:8.10.1
    container_name: create-collection
    environment:
      - SOLR_HOST=HSC
    networks:
      - solr
    command:
      - bash
      - "-e"
      - "-x"
      - "-c"
      - "wait-for-solr.sh --max-attempts 10 --wait-seconds 5 --solr-url http://$$SOLR_HOST:8983/; solr create_collection -c hsc-data -p 8983"

networks:
  solr: